### ISSUE TITLE
MSVS2013-built PE files have no DIRECTORY_ENTRY_DEBUG

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1214]
Causes plugin_replacement.py (from mumble-releng) to fail.

Not sure if DIRECTORY_ENTRY_DEBUG has been removed, or we're doing something wrong during the build.

Script output:

```
C:\dev\jenkins\workspace\Mumble Windows x86 (static)>"C:\dev\mumble-releng\tools\plugin_replacement.py" --version "1.2.5-268-gc897c56" --repo . release\plugins 
INFO:root:Collecting plugin creation dates
INFO:root:Retrieving 'aoc.dll'
INFO:root:Retrieving 'arma2.dll'
INFO:root:Retrieving 'bf1942.dll'
INFO:root:Retrieving 'bf2.dll'
INFO:root:Retrieving 'bf2142.dll'
INFO:root:Retrieving 'bf3.dll'
INFO:root:Retrieving 'bfbc2.dll'
INFO:root:Retrieving 'bfheroes.dll'
INFO:root:Retrieving 'blacklight.dll'
INFO:root:Retrieving 'borderlands.dll'
INFO:root:Retrieving 'borderlands2.dll'
INFO:root:Retrieving 'breach.dll'
INFO:root:Retrieving 'cod2.dll'
INFO:root:Retrieving 'cod4.dll'
INFO:root:Retrieving 'cod5.dll'
INFO:root:Retrieving 'codmw2.dll'
INFO:root:Retrieving 'codmw2so.dll'
INFO:root:Retrieving 'cs.dll'
INFO:root:Retrieving 'css.dll'
INFO:root:Retrieving 'dods.dll'
INFO:root:Retrieving 'dys.dll'
INFO:root:Retrieving 'etqw.dll'
INFO:root:Retrieving 'gmod.dll'
INFO:root:Retrieving 'gtaiv.dll'
INFO:root:Retrieving 'gw.dll'
INFO:root:Retrieving 'hl2dm.dll'
INFO:root:Retrieving 'insurgency.dll'
INFO:root:Retrieving 'jc2.dll'
INFO:root:Retrieving 'l4d.dll'
INFO:root:Retrieving 'l4d2.dll'
INFO:root:Retrieving 'link.dll'
INFO:root:Retrieving 'lol.dll'
INFO:root:Retrieving 'lotro.dll'
INFO:root:Retrieving 'manual.dll'
INFO:root:Retrieving 'sr.dll'
INFO:root:Retrieving 'sto.dll'
INFO:root:Retrieving 'tf2.dll'
INFO:root:Retrieving 'ut2004.dll'
INFO:root:Retrieving 'ut3.dll'
INFO:root:Retrieving 'ut99.dll'
INFO:root:Retrieving 'wolfet.dll'
INFO:root:Retrieving 'wow.dll'
INFO:root:Checking repo for new revisions
INFO:root:Re-using 'aoc.dll' created on 2014-04-05 19:24:37
Traceback (most recent call last):
  File "C:\dev\mumble-releng\tools\plugin_replacement.py", line 367, in <module>
    copyUnchangedPluginsToBuild(old_plugins)
  File "C:\dev\mumble-releng\tools\plugin_replacement.py", line 302, in copyUnchangedPluginsToBuild
    guid = getSymbolserverPdbGUID(dll)
  File "C:\dev\mumble-releng\tools\plugin_replacement.py", line 120, in getSymbolserverPdbGUID
    header = pe.DIRECTORY_ENTRY_DEBUG[0].struct
AttributeError: PE instance has no attribute 'DIRECTORY_ENTRY_DEBUG'
```

**Comment by ZeroAbility** [comment]
@mkrautz - Was there any results for this? Microsoft ended support for MSVC 2013 April 9, 2014. If newer versions of Qt and MSVC no longer have this issue, we could probably close this.

**Comment by davidebeatrici** [comment]
We switched to MSVC 2015 in 2016 anyway.
