### ISSUE TITLE
Murmur hangs when multiple user login simultaneously

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#3878]
Depends on the hardware fitting of a server, clients can take various time (<1s ~ 10s) from establishing a connection to fully logged in. If another user login at this time window, Murmur server freezes, stopping receiving any input other than SIGKILL. A Segmentation Fault or Kernel Panic may occur, if the count of users trying to login the server at the very same time is large.

**Comment by davidebeatrici** [comment]
Sounds like a race condition.

Could you run Murmur through GDB and get a backtrace when you encounter the issue, please?

**Comment by wfjsw** [comment]
```
#0  0x00007ffff67c3819 in __GI___poll (fds=0x555555c757c0, nfds=7, timeout=0) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff59fe136 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff59fe25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6e958e4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff6e446e1 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x0000555555750b3f in MurmurRPC::Wrapper::V1_AuthenticatorStream::read (this=0x7fffdc00ef30)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:120
#6  MurmurRPC::Wrapper::V1_AuthenticatorStream::writeRead (this=this@entry=0x7fffdc00ef30) at MurmurRPC.proto.Wrapper.cpp:1013
#7  0x000055555571f18d in MurmurRPCImpl::authenticateSlot (this=<optimized out>, res=<optimized out>, uname=..., sessionId=<optimized out>,
    certlist=..., certhash=..., certstrong=<optimized out>, pw=...) at MurmurGRPCImpl.cpp:415
#8  0x000055555577c618 in MurmurRPCImpl::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_MurmurGRPCImpl.cpp:179
#9  0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00005555557723b8 in Server::authenticateSig (this=this@entry=0x555555a2c7f0, _t1=<optimized out>, _t2=..., _t3=<optimized out>, _t4=...,
    _t5=..., _t6=<optimized out>, _t7=...) at ../../debug/.moc/murmur/moc_Server.cpp:575
#11 0x000055555565ef64 in Server::authenticate (this=this@entry=0x555555a2c7f0, name=..., password=..., sessionId=<optimized out>, emails=...,
    certhash=..., bStrongCert=false, certs=...) at ServerDB.cpp:1042
#12 0x000055555567f0a5 in Server::msgAuthenticate (this=this@entry=0x555555a2c7f0, uSource=uSource@entry=0x555555c83b80, msg=...) at Messages.cpp:105
#13 0x00005555556474c5 in Server::message (this=0x555555a2c7f0, uiType=<optimized out>, qbaMsg=..., u=0x555555c83b80, u@entry=0x0) at Server.cpp:1538
#14 0x00005555557730f2 in Server::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Server.cpp:301
#15 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00005555557711f6 in Connection::message (this=this@entry=0x555555c83b80, _t1=<optimized out>, _t2=...)
    at ../../debug/.moc/murmur/moc_Connection.cpp:239
#17 0x0000555555627d8c in Connection::socketRead (this=0x555555c83b80) at ../Connection.cpp:136
#18 0x0000555555771315 in Connection::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Connection.cpp:114
#19 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff7334e37 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#21 0x00007ffff7316de1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#22 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff72dcb53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#24 0x00007ffff72dcbe0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#25 0x00007ffff72eef31 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#26 0x00007ffff6e44586 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff6e9647a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff59fdf2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff59fe1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff59fe25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff6e9587b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6e4327b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff6e4b262 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00005555555ebdd8 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:583
```

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/blob/6195761d290fd3ba4296215e525da8008ddf86d2/docs/MurmurLocking.md

https://github.com/mumble-voip/mumble/blob/ccdb88f872b85e04733e1e39ed78b23142ab581c/src/murmur/Messages.cpp#L102-L105

https://github.com/mumble-voip/mumble/blob/ccdb88f872b85e04733e1e39ed78b23142ab581c/src/murmur/ServerDB.cpp#L1042

@hacst Aren't the functions in `Server` supposed to be guarded by a `QMutex`?

**Comment by wfjsw** [comment]
Is it possible to have a quick fix now? Seems a security issue here.

**Comment by Anankke** [comment]
True, this can be used as a dos trigger. Same issue here. Is there any possible quick fix?

**Comment by wfjsw** [comment]
So I added a new global QMutexLocker to `Server::msgAuthenticate`. The time usage for each login decreases significantly, but Segmentation Fault still exists and sometime crashes the whole system when load is high so I can't obtain backtracks. Any hints?

**Comment by wfjsw** [comment]
Got this message before crash in my syslog:
```
kernel: [ 5906.682905] traps: murmurd[2479] general protection fault ip:7f08d0284deb sp:7fff04b945c0 error:0 in libQt5Core.so.5.11.3[7f08d01cb000+2a4000]
```

**Comment by wfjsw** [comment]
After I progressed further into this matter, debugger shows deadlocks around

https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurGRPCImpl.cpp#L413-L420

Shouldn't there be a try catch here?

... and a segmentation fault point elsewhere around, triggered randomly. Need debugging assist, really.

**Comment by wfjsw** [comment]
```
#0  0x00007ffff72dd604 in QAbstractSocket::peerPort() const () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#1  0x000055555568086d in Server::msgAuthenticate (this=this@entry=0x555555a48860, uSource=uSource@entry=0x555556572df0, msg=...) at Messages.cpp:181
#2  0x00005555556477f5 in Server::message (this=0x555555a48860, uiType=<optimized out>, qbaMsg=..., u=0x555556572df0, u@entry=0x0) at Server.cpp:1538
#3  0x0000555555773682 in Server::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Server.cpp:301
#4  0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x0000555555771786 in Connection::message (this=this@entry=0x555556572df0, _t1=<optimized out>, _t2=...)
    at ../../debug/.moc/murmur/moc_Connection.cpp:239
#6  0x000055555562809c in Connection::socketRead (this=0x555556572df0) at ../Connection.cpp:136
#7  0x00005555557718a5 in Connection::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Connection.cpp:114
#8  0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff7334e37 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#10 0x00007ffff7316de1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#11 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff72dcb53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#13 0x00007ffff72dcbe0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#14 0x00007ffff72eef31 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#15 0x00007ffff6e44586 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6e9647a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff59fdf2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff59fe1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff59fe25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff6e95863 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6e4327b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6e4b262 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00005555555ebde8 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:583
```

**Comment by wfjsw** [comment]
Another Segmentation fault

```
#0  0x00007ffff6d92e13 in QIODevice::write(char const*, long long) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x0000555555627dc5 in QIODevice::write (data=..., this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h:61
#2  Connection::sendMessage (qbaMsg=..., this=<optimized out>) at ../Connection.cpp:178
#3  Connection::sendMessage (this=<optimized out>, msg=..., msgType=<optimized out>, cache=...) at ../Connection.cpp:173
#4  0x000055555563c8b7 in Server::sendProtoMessage (this=this@entry=0x555555a48860, u=u@entry=0x555559654ea0, msg=..., msgType=msgType@entry=15)
    at Server.cpp:1585
#5  0x000055555567fdd0 in Server::sendMessage (msg=..., u=0x555559654ea0, this=0x555555a48860) at Server.h:313
#6  Server::msgAuthenticate (this=this@entry=0x555555a48860, uSource=uSource@entry=0x555559654ea0, msg=...) at Messages.cpp:255
#7  0x00005555556477f5 in Server::message (this=0x555555a48860, uiType=<optimized out>, qbaMsg=..., u=0x555559654ea0, u@entry=0x0) at Server.cpp:1538
#8  0x0000555555773682 in Server::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Server.cpp:301
#9  0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x0000555555771786 in Connection::message (this=this@entry=0x555559654ea0, _t1=<optimized out>, _t2=...)
    at ../../debug/.moc/murmur/moc_Connection.cpp:239
#11 0x000055555562809c in Connection::socketRead (this=0x555559654ea0) at ../Connection.cpp:136
#12 0x00005555557718a5 in Connection::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ../../debug/.moc/murmur/moc_Connection.cpp:114
#13 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff7334e37 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#15 0x00007ffff7316de1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#16 0x00007ffff6e6d906 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff72dcb53 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#18 0x00007ffff72dcbe0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#19 0x00007ffff72eef31 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#20 0x00007ffff6e44586 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6e9647a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff59fdf2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff59fe1c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff59fe25c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff6e95863 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6e4327b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff6e4b262 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00005555555ebde8 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:583
```

**Comment by seantalts** [comment]
Is this still happening? I can't seem to reproduce it.

**Comment by Anankke** [comment]
You can easily reproduce this as the auth process takes such long time to finish.

**Comment by seantalts** [comment]
I'm having 200 botamusique bots join at almost exactly the same time and not seeing any hangs or crashes... is there a step I'm missing?

**Comment by wfjsw** [comment]
Use a external authenticator that respond slowly.

**Comment by wfjsw** [comment]
Closing this since:
 - I suspect it's a gRPC issue and gRPC support got removed by #5552.
 - Nobody seems to be able to reproduce this, nor in similar fashion in 2 years.
 - I stopped using Murmur and switched to my own server implemention since then, thus no resource is available to further work on this.
