### ISSUE TITLE
Git version crashes after a while

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#5373]
### Description

I compiled the current Git version 7419dbf28899f64f8a6e5b59d33815776a845c06 and after a while Mumble crashes.

### Steps to reproduce

It only happens when I am not muted and deafened. Seems to happen to some Arch users as well (I'm using Gentoo)

### Mumble version

7419dbf28899f64f8a6e5b59d33815776a845c06

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
Thread 0x7fffe9c03640 (LWP 67693) exited]
malloc(): unsorted double linked list corrupted

Thread 19 "ServerHandler" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb4a9c640 (LWP 67704)]
0x00007ffff5adced1 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5adced1 in raise () at /lib64/libc.so.6
#1  0x00007ffff5ac7536 in abort () at /lib64/libc.so.6
#2  0x00007ffff5b1dec8 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff5b258da in  () at /lib64/libc.so.6
#4  0x00007ffff5b28ecc in _int_malloc () at /lib64/libc.so.6
#5  0x00007ffff5b2b121 in calloc () at /lib64/libc.so.6
#6  0x00007ffff77421c1 in jitter_buffer_put () at /usr/lib64/libspeexdsp.so.1
#7  0x00005555556687a8 in AudioOutputSpeech::addFrameToBuffer(QByteArray const&, unsigned int) ()
#8  0x0000555555664caa in AudioOutput::addFrameToBuffer(ClientUser*, QByteArray const&, unsigned int, MessageHandler::UDPMessageType) ()
#9  0x00005555557631fd in ServerHandler::handleVoicePacket(unsigned int, PacketDataStream&, MessageHandler::UDPMessageType) ()
#10 0x0000555555765ddc in ServerHandler::udpReady() ()
#11 0x00007ffff626a810 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff6d00bbf in QAbstractSocketPrivate::canReadNotification() () at /usr/lib64/libQt5Network.so.5
#13 0x00007ffff6d13721 in QReadNotifier::event(QEvent*) () at /usr/lib64/libQt5Network.so.5
#14 0x00007ffff78ed69f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff6237ff8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff6288e0e in socketNotifierSourceDispatch(_GSource*, int (*)(void*), void*) () at /usr/lib64/libQt5Core.so.5
#17 0x00007ffff4eb155f in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff4eb1a58 in g_main_context_iterate.constprop () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff4eb1b0f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff62883e3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#21 0x00007ffff6236ac3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#22 0x00007ffff608c107 in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#23 0x000055555576576b in ServerHandler::run() ()
#24 0x00007ffff608d255 in QThreadPrivate::start(void*) () at /usr/lib64/libQt5Core.so.5
#25 0x00007ffff7433d2e in start_thread () at /lib64/libpthread.so.0
#26 0x00007ffff5b9b7cf in clone () at /lib64/libc.so.6
```

**Comment by Krzmbrzl** [comment]
This might be a side-effect caused by #5361 for which I just merged a fix. Could you check whether the issue persists?

**Comment by promi** [comment]
Works fine now, thanks.

**Comment by Krzmbrzl** [comment]
Great! :+1:
