### ISSUE TITLE
Mumble freezing on sound system reload with pipewire

### ISSUE THREAD

**Issue by dexgs** [mumble-voip/mumble#5647]
### Description

Mumble becomes unresponsive after performing some actions and must be killed manually before another instance can be opened (without using the -m flag).

### Steps to reproduce

1. Install pipewire with version >= 0.3.51 and use it as your sound system
2. Set mumble's sound system to pipewire
3. perform any action that causes the sound system to un-load at some point (applying settings, closing mumble, using the setup wizard, etc.)

### Mumble version

1.4.230

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

I attached strace to a mumble client experiencing the issue and saw that it gets blocked on a read operation on some message queue. I was able to reproduce the issue on my desktop and laptop computers. In both cases, I solved the problem by changing the sound system to PulseAudio.

**Comment by dexgs** [comment]
I just remembered that it won't freeze if you quit while connected to a server. It *does* freeze if you quit while not connected to a server, though.

**Comment by vimpostor** [comment]
Confirmed, here is a backtrace with additional Pipewire 0.3.51 debug symbols:

```c++
Thread 1 "mumble" received signal SIGINT, Interrupt.
0x00007ffff572a1ec in read () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff572a1ec in read () at /usr/lib/libc.so.6
#1  0x00007fffea2582a8 in read
    (__nbytes=8, __buf=<optimized out>, __fd=<optimized out>, __fd=<optimized out>, __buf=<optimized out>, __nbytes=<optimized out>)
    at /usr/include/bits/unistd.h:38
#2  impl_eventfd_read (object=<optimized out>, fd=<optimized out>, count=<optimized out>) at ../pipewire/spa/plugins/support/system.c:234
#3  0x00007fffea24cb71 in loop_invoke
    (object=0x555557027618, func=0x7fffea2c0e70 <do_node_remove>, seq=<optimized out>, data=<optimized out>, size=0, block=<optimized out>, user_data=<optimized out>) at ../pipewire/spa/plugins/support/loop.c:285
#4  0x00007fffea2cdeb0 in pw_impl_node_set_active (active=false, node=0x555557080170) at ../pipewire/src/pipewire/impl-node.c:2228
#5  pw_impl_node_set_active (node=0x555557080170, active=false) at ../pipewire/src/pipewire/impl-node.c:2212
#6  0x00007fffea2ef002 in pw_stream_disconnect (stream=0x555556f94810) at ../pipewire/src/pipewire/stream.c:2007
#7  0x00007fffea2ec189 in pw_stream_destroy (stream=0x555556f94810) at ../pipewire/src/pipewire/stream.c:1583
#8  0x0000555555945b8d in PipeWireEngine::~PipeWireEngine() (this=0x555556fa1a60, __in_chrg=<optimized out>)
    at /home/magnus/Documents/Qt/mumble/src/mumble/PipeWire.cpp:222
#9  0x0000555555947f00 in std::default_delete<PipeWireEngine>::operator()(PipeWireEngine*) const (this=0x555556fa63f8, __ptr=0x555556fa1a60)
    at /usr/include/c++/11.2.0/bits/unique_ptr.h:85
#10 0x00005555559472c2 in std::unique_ptr<PipeWireEngine, std::default_delete<PipeWireEngine> >::~unique_ptr()
    (this=0x555556fa63f8, __in_chrg=<optimized out>) at /usr/include/c++/11.2.0/bits/unique_ptr.h:361
#11 0x00005555559464cc in PipeWireOutput::~PipeWireOutput() (this=0x555556fa6390, __in_chrg=<optimized out>)
    at /home/magnus/Documents/Qt/mumble/src/mumble/PipeWire.cpp:394
#12 0x00005555559464f4 in PipeWireOutput::~PipeWireOutput() (this=0x555556fa6390, __in_chrg=<optimized out>)
    at /home/magnus/Documents/Qt/mumble/src/mumble/PipeWire.cpp:394
#13 0x00005555556710fb in boost::checked_delete<AudioOutput>(AudioOutput*) (x=0x555556fa6390) at /usr/include/boost/core/checked_delete.hpp:36
#14 0x00005555556714c8 in boost::detail::sp_counted_impl_p<AudioOutput>::dispose() (this=0x555556f9c720)
    at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:89
#15 0x0000555555657e89 in boost::detail::sp_counted_base::release() (this=0x555556f9c720)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#16 0x0000555555657eff in boost::detail::shared_count::~shared_count() (this=0x7fffffffd378, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#17 0x0000555555657f76 in boost::shared_ptr<AudioOutput>::~shared_ptr() (this=0x7fffffffd370, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
#18 0x000055555565b4e3 in boost::shared_ptr<AudioOutput>::reset() (this=0x7fffffffd3a0) at /usr/include/boost/smart_ptr/shared_ptr.hpp:729
#19 0x000055555565a3f7 in Audio::stop() () at /home/magnus/Documents/Qt/mumble/src/mumble/Audio.cpp:287
#20 0x000055555595981a in main(int, char**) (argc=1, argv=0x7fffffffdbe8) at /home/magnus/Documents/Qt/mumble/src/mumble/main.cpp:842
```
