### ISSUE TITLE
Mumble crashes on startup with Pipewire 0.3.68

### ISSUE THREAD

**Issue by Majora320** [mumble-voip/mumble#6101]
### Description

When starting mumble, the program segfaults. This started occurring after wiping my settings to try to fix a separate bug. I'm currently using pipewire and pipewire-pulse. Previously, I had mumble configured to accept input from Pulseaudio, and it worked with no issues.

### Steps to reproduce

1. Delete ~/.config/Mumble
2. Start mumble

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
#0  0x00007fffeb9a88c4 in impl_check (data=0x555556b6fbd0, loop=0x555556b380f0) at ../pipewire/src/pipewire/thread-loop.c:95
#1  0x00007fffeb9ab043 in pw_stream_destroy (stream=0x555556b6e6d0) at ../pipewire/src/pipewire/stream.c:1652
#2  0x00005555557ef62f in PipeWireEngine::~PipeWireEngine() (this=0x555556c9d880, this=<optimized out>) at /usr/include/c++/12.2.1/bits/unique_ptr.h:191
#3  std::default_delete<PipeWireEngine>::operator()(PipeWireEngine*) const (this=<optimized out>, __ptr=0x555556c9d880) at /usr/include/c++/12.2.1/bits/unique_ptr.h:95
#4  std::default_delete<PipeWireEngine>::operator()(PipeWireEngine*) const (__ptr=0x555556c9d880, this=<optimized out>) at /usr/include/c++/12.2.1/bits/unique_ptr.h:89
#5  std::unique_ptr<PipeWireEngine, std::default_delete<PipeWireEngine> >::~unique_ptr() (this=0x555556b5ef80, this=<optimized out>) at /usr/include/c++/12.2.1/bits/unique_ptr.h:396
#6  PipeWireInput::~PipeWireInput() (this=0x555556b5e730, this=<optimized out>) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/PipeWire.cpp:336
#7  0x00005555557ef68d in PipeWireInput::~PipeWireInput() (this=0x555556b5e730, this=<optimized out>) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/PipeWire.cpp:336
#8  0x0000555555693a15 in boost::detail::sp_counted_base::release() (this=0x555556c68f80) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#9  boost::detail::sp_counted_base::release() (this=0x555556c68f80) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:116
#10 boost::detail::shared_count::~shared_count() (this=<optimized out>, this=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#11 boost::shared_ptr<AudioInput>::~shared_ptr() (this=<optimized out>, this=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
#12 boost::shared_ptr<AudioInput>::reset() (this=<synthetic pointer>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:726
#13 Audio::stop() () at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/Audio.cpp:234
#14 0x00005555556ad324 in AudioWizard::restartAudio() (this=0x555556d051d0) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/AudioWizard.cpp:367
#15 0x000055555563b181 in AudioWizard::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_a=0x7fffffffdec0, _id=4, _c=QMetaObject::InvokeMetaMethod, _o=0x555556d051d0)
    at /usr/src/debug/mumble/build-client/src/mumble/mumble_client_object_lib_autogen/EWIEGA46WW/moc_AudioWizard.cpp:151
#16 AudioWizard::qt_metacall(QMetaObject::Call, int, void**) (this=0x555556d051d0, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffdec0) at /usr/src/debug/mumble/build-client/src/mumble/mumble_client_object_lib_autogen/EWIEGA46WW/moc_AudioWizard.cpp:215
#17 0x00007ffff5cbe93d in doActivate<false>(QObject*, int, void**) (sender=0x555556da27c0, signal_index=7, argv=0x7fffffffdec0) at kernel/qobject.cpp:3949
#18 0x00007ffff6a65253 in QAbstractSlider::valueChanged(int) (this=this@entry=0x555556da27c0, _t1=<optimized out>, _t1@entry=5) at .moc/moc_qabstractslider.cpp:309
#19 0x00007ffff6a66cbd in QAbstractSlider::setValue(int) (this=0x555556da27c0, value=5) at widgets/qabstractslider.cpp:548
#20 0x00005555556b3dfa in AudioWizard::AudioWizard(QWidget*) (this=0x555556d051d0, p=<optimized out>, this=<optimized out>, p=<optimized out>) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/Global.cpp:24
#21 0x000055555561a34b in std::make_unique<AudioWizard, MainWindow*&>(MainWindow*&) () at /usr/include/c++/12.2.1/bits/unique_ptr.h:1064
#22 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/main.cpp:742
```

**Comment by Krzmbrzl** [comment]
Seems like the crash is originating from the audio wizard...
@davidebeatrici could you have a look please?

**Comment by 100espressos** [comment]
**Mumble version**
 1.5.517-1 and my build of yesterday's git head revision.

**Mumble component**
 Client

**OS**
 Linux

**Reproducible?**
 Yes

**Additional information**

I could not yet find a problem in my audio stack, which seems to be working normally (recording, etc.).

Note the output from libpipewire; it also appears in crash reports of some other projects (espeak) that seem to be using a similar method.

```
PIPEWIRE_DEBUG=2 gdb mumble
Reading symbols from mumble...
Reading symbols from .cache/debuginfod_client/ab24f2d99d99cf5005d07405c5c215da1bde0375/debuginfo...
(gdb) run
Starting program: /usr/bin/mumble
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1ec96c0 (LWP 2164)]
[New Thread 0x7ffff16c86c0 (LWP 2165)]
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
[New Thread 0x7fffe9bdd6c0 (LWP 2166)]
[Thread 0x7fffe9bdd6c0 (LWP 2166) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2168)]
[Thread 0x7fffe9bdd6c0 (LWP 2168) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2170)]
[Thread 0x7fffe9bdd6c0 (LWP 2170) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2172)]
[Thread 0x7fffe9bdd6c0 (LWP 2172) exited]
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
[New Thread 0x7fffe9bdd6c0 (LWP 2173)]
[New Thread 0x7fffe93826c0 (LWP 2175)]
[Thread 0x7fffe93826c0 (LWP 2175) exited]
[Thread 0x7fffe9bdd6c0 (LWP 2173) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2176)]
[New Thread 0x7fffe93826c0 (LWP 2178)]
[Thread 0x7fffe93826c0 (LWP 2178) exited]
[Thread 0x7fffe9bdd6c0 (LWP 2176) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2179)]
[Thread 0x7fffe9bdd6c0 (LWP 2179) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2180)]
[Thread 0x7fffe9bdd6c0 (LWP 2180) exited]
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
[New Thread 0x7fffe9bdd6c0 (LWP 2181)]
[New Thread 0x7fffe93826c0 (LWP 2183)]
[Thread 0x7fffe93826c0 (LWP 2183) exited]
[Thread 0x7fffe9bdd6c0 (LWP 2181) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2185)]
[New Thread 0x7fffe93826c0 (LWP 2187)]
[Thread 0x7fffe93826c0 (LWP 2187) exited]
[Thread 0x7fffe9bdd6c0 (LWP 2185) exited]
[New Thread 0x7fffe9bdd6c0 (LWP 2188)]
[New Thread 0x7fffe9bdd6c0 (LWP 2190)]
[Thread 0x7fffe9bdd6c0 (LWP 2188) exited]
[New Thread 0x7fffe93826c0 (LWP 2191)]
[New Thread 0x7fffcbdff6c0 (LWP 2193)]
[New Thread 0x7fffcb5fe6c0 (LWP 2194)]
[New Thread 0x7fffca1ff6c0 (LWP 2195)]
[New Thread 0x7fffc99fe6c0 (LWP 2196)]
[New Thread 0x7fffc91fd6c0 (LWP 2197)]
[New Thread 0x7fffc89fc6c0 (LWP 2198)]
[New Thread 0x7fffb3bff6c0 (LWP 2199)]
[W][00954.063652] default      | [        thread.c:  101 impl_acquire_rt()] acquire_rt thread:0x7fffb3bff6c0 prio:-1 not implemented
[New Thread 0x7fffb33fe6c0 (LWP 2200)]
[New Thread 0x7fffb2bfd6c0 (LWP 2201)]
[Thread 0x7fffb2bfd6c0 (LWP 2201) exited]
[New Thread 0x7fffb2bfd6c0 (LWP 2202)]
[W][00954.094983] default      | [        thread.c:  101 impl_acquire_rt()] acquire_rt thread:0x7fffb2bfd6c0 prio:-1 not implemented
[New Thread 0x7fffb23fc6c0 (LWP 2203)]
[New Thread 0x7fffb1bfb6c0 (LWP 2204)]
[Thread 0x7fffb1bfb6c0 (LWP 2204) exited]
[Thread 0x7fffb33fe6c0 (LWP 2200) exited]
warning: The VAD has been replaced by a hack pending a complete rewrite

Thread 1 "mumble" received signal SIGSEGV, Segmentation fault.
0x00007fffea2a08c4 in impl_check (data=0x555556eb98a0, loop=0x555556ef46b0) at ../pipewire/src/pipewire/thread-loop.c:95
95              if (spa_loop_control_check(this->loop->control) == 1)
(gdb) bt
#0  0x00007fffea2a08c4 in impl_check (data=0x555556eb98a0, loop=0x555556ef46b0) at ../pipewire/src/pipewire/thread-loop.c:95
#1  0x00007fffea2a3043 in pw_stream_destroy (stream=0x555556eba6a0) at ../pipewire/src/pipewire/stream.c:1652
#2  0x00005555557ef62f in PipeWireEngine::~PipeWireEngine() (this=0x555556ef5cc0, this=<optimized out>)
    at /usr/include/c++/12.2.1/bits/unique_ptr.h:191
#3  std::default_delete<PipeWireEngine>::operator()(PipeWireEngine*) const (this=<optimized out>, __ptr=0x555556ef5cc0)
    at /usr/include/c++/12.2.1/bits/unique_ptr.h:95
#4  std::default_delete<PipeWireEngine>::operator()(PipeWireEngine*) const (__ptr=0x555556ef5cc0, this=<optimized out>)
    at /usr/include/c++/12.2.1/bits/unique_ptr.h:89
#5  std::unique_ptr<PipeWireEngine, std::default_delete<PipeWireEngine> >::~unique_ptr() (this=0x555556ef3b70, this=<optimized out>)
    at /usr/include/c++/12.2.1/bits/unique_ptr.h:396
#6  PipeWireInput::~PipeWireInput() (this=0x555556ef3320, this=<optimized out>)
    at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/PipeWire.cpp:336
#7  0x00005555557ef68d in PipeWireInput::~PipeWireInput() (this=0x555556ef3320, this=<optimized out>)
    at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/PipeWire.cpp:336
#8  0x0000555555693a15 in boost::detail::sp_counted_base::release() (this=0x555556ea7640)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:120
#9  boost::detail::sp_counted_base::release() (this=0x555556ea7640) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:116
#10 boost::detail::shared_count::~shared_count() (this=<optimized out>, this=<optimized out>)
    at /usr/include/boost/smart_ptr/detail/shared_count.hpp:432
#11 boost::shared_ptr<AudioInput>::~shared_ptr() (this=<optimized out>, this=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:335
#12 boost::shared_ptr<AudioInput>::reset() (this=<synthetic pointer>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:726
#13 Audio::stop() () at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/Audio.cpp:234
#14 0x00005555556ad324 in AudioWizard::restartAudio() (this=0x555556f59da0)
    at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/AudioWizard.cpp:367
#15 0x000055555563b181 in AudioWizard::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_a=0x7fffffffd9b0, _id=4, _c=QMetaObject::InvokeMetaMethod, _o=0x555556f59da0)
    at /usr/src/debug/mumble/build-client/src/mumble/mumble_client_object_lib_autogen/EWIEGA46WW/moc_AudioWizard.cpp:151
#16 AudioWizard::qt_metacall(QMetaObject::Call, int, void**) (this=0x555556f59da0, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffd9b0)
    at /usr/src/debug/mumble/build-client/src/mumble/mumble_client_object_lib_autogen/EWIEGA46WW/moc_AudioWizard.cpp:215
#17 0x00007ffff5cbe93d in doActivate<false>(QObject*, int, void**) (sender=0x555556fd5e00, signal_index=7, argv=0x7fffffffd9b0)
    at kernel/qobject.cpp:3949
#18 0x00007ffff6a65253 in QAbstractSlider::valueChanged(int) (this=this@entry=0x555556fd5e00, _t1=<optimized out>, _t1@entry=5)
    at .moc/moc_qabstractslider.cpp:309
#19 0x00007ffff6a66cbd in QAbstractSlider::setValue(int) (this=0x555556fd5e00, value=5) at widgets/qabstractslider.cpp:548
#20 0x00005555556b3dfa in AudioWizard::AudioWizard(QWidget*) (this=0x555556f59da0, p=<optimized out>, this=<optimized out>, p=<optimized out>)
    at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/Global.cpp:24
#21 0x000055555561a34b in std::make_unique<AudioWizard, MainWindow*&>(MainWindow*&) () at /usr/include/c++/12.2.1/bits/unique_ptr.h:1064
#22 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mumble/mumble-1.5.517/src/mumble/main.cpp:742

```

**Comment by 100espressos** [comment]
> What version of Pipewire are you using (both of you)?
(lib)pipewire 0.3.68-1

**Comment by 100espressos** [comment]
Configuration details, with rear panel playback, front panel capture.

```
$ cat /proc/asound/pcm

00-00: ALC892 Analog : ALC892 Analog : playback 1 : capture 1
00-01: ALC892 Digital : ALC892 Digital : playback 1
00-02: ALC892 Alt Analog : ALC892 Alt Analog : capture 1
01-03: HDMI 0 : HDMI 0 : playback 1
01-07: HDMI 1 : HDMI 1 : playback 1
01-08: HDMI 2 : HDMI 2 : playback 1
01-09: HDMI 3 : HDMI 3 : playback 1
```
```
$ arecord -l

**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC892 Alt Analog [ALC892 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
```
$ wpctl status #abridged

PipeWire 'pipewire-0' [0.3.68]
Audio
 ├─ Devices:
 │    40. GM204 High Definition Audio Controller [alsa]
 │    41. Built-in Audio                      [alsa]
 ├─ Sinks:
 │  * 46. Built-in Audio Analog Stereo        [vol: 1.00]
 ├─ Sink endpoints:
 ├─ Sources:
 │    47. Built-in Audio Analog Stereo        [vol: 1.00]
 ├─ Source endpoints:
 └─ Streams:

Settings
 └─ Default Configured Node Names:
    0. Audio/Sink    alsa_output.pci-0000_00_1b.0.analog-stereo
    1. Audio/Source  alsa_output.pci-0000_00_1b.0.analog-stereo
```
```$ pactl list sources```
http://ix.io/4t9f

**Comment by Majora320** [comment]
> What version of Pipewire are you using (both of you)? Perhaps they have (again) updated the API semantics and therefore we'd have to access it in a different way?

I was also using 0.3.68. I tried downgrading Pipewire to 0.3.67 and Mumble started normally without crashing, so this bug was likely introduced between the two versions.

**Comment by 100espressos** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3150#note_1862593

> Wim Taymans:
> mumble destroys the thread loop before the stream: https://github.com/mumble-voip/mumble/blob/master/src/mumble/PipeWire.cpp#L216
> 
> First destroy the stream, then the thread loop.

**Comment by Krzmbrzl** [comment]
Ah. Thanks for the info :+1: 
Is someone here capable of building Mumble from source in order to verify that #6103 indeed fixes the crash?

**Comment by ruineka** [comment]
> Possibly related: [ValveSoftware/steam-for-linux#9337](https://github.com/ValveSoftware/steam-for-linux/issues/9337)

This commit fixes the issue for me https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/8748c77451ce332dd24549b414200499ede4f184

**Comment by Krzmbrzl** [comment]
Great! Thanks for testing :+1:
